#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
build_lessons.py — render every lesson PDF (PDF format 00 · full-spectrum) and the generated READMEs.

    python 0-script/build_lessons.py                 # all lessons
    python 0-script/build_lessons.py --only 3 7      # lessons 03 and 07
    python 0-script/build_lessons.py --only 3 --qa   # + rasterize pages for visual QA (.build/qa/)
    python 0-script/build_lessons.py --list          # lesson roster, nothing rendered

Each lesson is a module 0-script/lessons/lesson_NN.py exposing META (dict) and blocks() (list).
Output: lesson-NN-<slug>/lesson-NN-<slug>.pdf + lesson-NN-<slug>/README.md, and the lesson table
between the LESSONS markers in the root README.md. Scratch files go to .build/ (gitignored).

Renderer: 0-script/_lib/brief_pdf.py (vendored — see _lib/VENDORED.md). Set BRIEF_PDF_HOME to a
folder holding a newer brief_pdf.py / chart_svg.py to render with that copy instead.
Contract: 1-analysis/spec_lesson-pdfs/_standard.md
"""
import argparse
import datetime
import importlib
import json
import os
import pathlib
import re
import subprocess
import sys

HERE = pathlib.Path(__file__).resolve().parent
REPO = HERE.parent
sys.stdout.reconfigure(encoding="utf-8")
sys.path.insert(0, str(HERE / "_lib"))
if os.environ.get("BRIEF_PDF_HOME"):
    sys.path.insert(0, os.environ["BRIEF_PDF_HOME"])
sys.path.insert(0, str(HERE))

import brief_pdf  # noqa: E402
from lesson_kit import lint_blocks  # noqa: E402

MARK_START, MARK_END = "<!-- LESSONS:START -->", "<!-- LESSONS:END -->"
SPEC_DIR = REPO / "1-analysis" / "spec_lesson-pdfs"


def lesson_modules(only=None):
    """Import lesson modules. With `only`, import just those numbers — so a lesson that is mid-edit
    (or broken) elsewhere in the tree never stops another lesson from building."""
    mods = []
    for p in sorted((HERE / "lessons").glob("lesson_[0-9][0-9].py")):
        if only and int(p.stem.split("_")[1]) not in only:
            continue
        mods.append(importlib.import_module(f"lessons.{p.stem}"))
    return mods


def folder(meta):
    return REPO / f"lesson-{meta['num']:02d}-{meta['slug']}"


def title(meta):
    return f"Lesson {meta['num']:02d} · {meta['title']}"


def sample_projects(meta):
    root = folder(meta) / "samples"
    if not root.exists():
        return []
    return sorted(p for p in root.rglob("*") if p.suffix in (".csproj", ".vbproj"))


def write_lesson_readme(meta):
    d = folder(meta)
    name = d.name
    lines = [f"<!-- generated by 0-script/build_lessons.py from META in 0-script/lessons/lesson_{meta['num']:02d}.py — do not hand-edit -->",
             f"# {title(meta)}", "", f"> {meta['subtitle']}", "",
             f"📄 **Lesson PDF:** [{name}.pdf](./{name}.pdf)", "",
             "## You will be able to", ""]
    lines += [f"- {o}" for o in meta["objectives"]]
    lines += ["", "## Maps from your stack", "", meta["maps_from"], ""]
    projs = sample_projects(meta)
    if projs:
        lines += ["## Samples — every code panel in the PDF is read from these files", "",
                  "| Project | Language | Build / run |", "|---|---|---|"]
        for p in projs:
            rel = p.relative_to(d).as_posix()
            lang = "C#" if p.suffix == ".csproj" else "Visual Basic"
            lines.append(f"| [`{p.stem}`](./{rel}) | {lang} | `dotnet build {rel}` |")
        lines.append("")
    lines += ["## Rebuild", "", "```bash",
              f"python 0-script/build_lessons.py --only {meta['num']}   # this PDF",
              f"python 0-script/verify_samples.py --only {meta['num']}  # build + test + run the samples",
              "```", ""]
    (d / "README.md").write_text("\n".join(lines), encoding="utf-8")


def write_root_index(mods):
    readme = REPO / "README.md"
    text = readme.read_text(encoding="utf-8")
    if MARK_START not in text or MARK_END not in text:
        print("  ! root README.md has no LESSONS markers — index not written")
        return
    rows = ["| # | Lesson | PDF | Maps from | Samples |", "|---|---|---|---|---|"]
    for m in mods:
        meta = m.META
        d = folder(meta)
        n = len(sample_projects(meta))
        rows.append(f"| {meta['num']:02d} | [{meta['title']}](./{d.name}/README.md) | "
                    f"[pdf](./{d.name}/{d.name}.pdf) | {meta['maps_from_short']} | {n} project(s) |")
    head, rest = text.split(MARK_START, 1)
    _old, tail = rest.split(MARK_END, 1)
    readme.write_text(head + MARK_START + "\n" + "\n".join(rows) + "\n" + MARK_END + tail, encoding="utf-8")


def lint_pdf(pdf):
    """Problems visible only in the rendered PDF: diagrams or charts that silently fell back."""
    from pypdf import PdfReader

    text = "\n".join(pg.extract_text() or "" for pg in PdfReader(str(pdf)).pages)
    problems = []
    if "diagram not rendered" in text:
        problems.append("a mermaid diagram was not rendered (fell back to its source) — fix its syntax")
    problems += [f"chart '{m.group(1)}' failed to render" for m in re.finditer(r"chart (\w+) failed", text)]
    return problems


def write_manifest(mods):
    """Stage provenance for every unit (1-analysis/spec_lesson-pdfs/_manifest.json)."""
    from pypdf import PdfReader

    try:
        commit = subprocess.run(["git", "rev-parse", "--short", "HEAD"], cwd=REPO, capture_output=True,
                                text=True, timeout=20).stdout.strip() or None
    except Exception:  # noqa: BLE001
        commit = None
    files = {}
    for m in mods:
        meta = m.META
        d = folder(meta)
        pdf = d / f"{d.name}.pdf"
        spec = SPEC_DIR / f"{d.name}.md"
        if not spec.exists():
            print(f"  ! no unit spec for {d.name} (expected {spec.relative_to(REPO).as_posix()})")
        files[f"{d.name}/{d.name}.pdf"] = {
            "kind": "generated",
            "spec": spec.relative_to(REPO).as_posix(),
            "builder": "0-script/build_lessons.py",
            "data": [f"0-script/lessons/lesson_{meta['num']:02d}.py", "0-script/lessons/roster.py",
                     "0-script/_lib/lesson_kit.py"],
            "sources": [f"{d.name}/samples/"] if (d / "samples").exists() else [],
            "gate": "0-script/verify_samples.py",
            "pdf_style": "full-spectrum",
            "style_note": "PDF format 00 · Full Spectrum — brief_pdf.py block renderer + lesson_kit code panels",
            "pages": len(PdfReader(str(pdf)).pages) if pdf.exists() else None,
            "readme": f"{d.name}/README.md",
        }
    manifest = {"version": 2, "stage": "lesson-NN-<slug>", "revision": 1,
                "built_from": {"commit": commit, "generated": datetime.date.today().isoformat()},
                "spec": "1-analysis/spec_lesson-pdfs/", "files": files}
    (SPEC_DIR / "_manifest.json").write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n",
                                             encoding="utf-8")


def qa_render(pdf, num):
    """Rasterize every page, plus 2x2 contact sheets, into .build/qa/lesson-NN/."""
    import fitz  # PyMuPDF

    out = REPO / ".build" / "qa" / f"lesson-{num:02d}"
    out.mkdir(parents=True, exist_ok=True)
    for old in out.glob("*.png"):
        old.unlink()
    src = fitz.open(pdf)
    for i, page in enumerate(src):
        page.get_pixmap(matrix=fitz.Matrix(110 / 72, 110 / 72)).save(out / f"page-{i + 1:02d}.png")
    w, h = src[0].rect.width, src[0].rect.height
    sheet = fitz.open()
    for s in range(0, len(src), 4):
        pg = sheet.new_page(width=2 * w, height=2 * h)
        for k in range(4):
            if s + k < len(src):
                r = fitz.Rect((k % 2) * w, (k // 2) * h, (k % 2 + 1) * w, (k // 2 + 1) * h)
                pg.show_pdf_page(r, src, s + k)
                pg.draw_rect(r, color=(0.6, 0.6, 0.6), width=1)
    for j, pg in enumerate(sheet):
        pg.get_pixmap(matrix=fitz.Matrix(0.62, 0.62)).save(out / f"sheet-{j + 1:02d}.png")
    print(f"  qa   {out.relative_to(REPO).as_posix()}  ({len(src)} pages, {len(sheet)} sheets)")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--only", nargs="*", type=int, help="lesson numbers to build")
    ap.add_argument("--qa", action="store_true", help="rasterize pages for visual QA")
    ap.add_argument("--list", action="store_true", help="print the roster and exit")
    ap.add_argument("--no-index", action="store_true",
                    help="skip the root README lesson table and _manifest.json (use when lessons build concurrently)")
    ap.add_argument("--lint-only", action="store_true", help="check the lesson standard, render nothing")
    args = ap.parse_args()

    if args.list:
        for m in lesson_modules():
            print(f"{m.META['num']:02d}  {folder(m.META).name}  —  {m.META['title']}")
        return
    todo = lesson_modules(args.only)
    if args.only and len(todo) != len(set(args.only)):
        missing = sorted(set(args.only) - {m.META["num"] for m in todo})
        raise SystemExit(f"no lesson module for: {missing}")

    from pypdf import PdfReader

    failed = []
    for m in todo:
        meta = m.META
        d = folder(meta)
        pdf = d / f"{d.name}.pdf"
        tmp = REPO / ".build" / f"lesson-{meta['num']:02d}"
        print(f"lesson {meta['num']:02d}  {meta['title']}")
        blocks = m.blocks()
        errs = lint_blocks(blocks)
        if errs:
            print("  LINT FAILED — _standard.md §3:")
            for e in errs:
                print(f"    - {e}")
            failed.append(meta["num"])
            continue
        print("  lint ok")
        if args.lint_only:
            continue
        brief_pdf.render_brief(pdf, title(meta), meta["subtitle"], blocks, tmp_dir=tmp)
        print(f"  pdf  {pdf.relative_to(REPO).as_posix()}  ({len(PdfReader(str(pdf)).pages)} pages)")
        problems = lint_pdf(pdf)
        for p in problems:
            print(f"  RENDER PROBLEM: {p}")
        if problems:
            failed.append(meta["num"])
        write_lesson_readme(meta)
        if args.qa:
            qa_render(pdf, meta["num"])
    if not args.no_index and not args.lint_only:
        all_mods = lesson_modules()
        write_root_index(all_mods)
        write_manifest(all_mods)
    if failed:
        raise SystemExit(f"FAILED lessons: {failed}")


if __name__ == "__main__":
    main()
